package:
  name: sacvision
  version: "0.0.1"

requirements:
  build:
    - python >=3.10
    - setuptools

  run:
    - python
    - numpy
    - matplotlib
    - opencv

source:
  path: ..
 
build:
  number: 1
  entry_points:
    - sacvision = sacvision.sacvisionapp:main
  noarch: python

