name: sacvision
summary: A demonstration of the power of computer vision technology
description: |
      This program lets to acqurire images from a camera and to apply some 
      filters. It's programmed in python and it provides a Qt GUI to
      run the operations.
version: 0.0.1
license: AGPL-3.0
icon: snap/gui/sacvision.png
grade: devel
confinement: strict
base: core20
architectures:
  - build-on: [amd64]
compression: lzo

apps:
  sacvision:
    command: bin/sacvision
    environment:
      DISABLE_WAYLAND: 1
      QT_XKB_CONFIG_ROOT: $SNAP/share/X11/xkb
      GTS_PLUGIN_PATH: $SNAP/lib/gstreamer-1.0
    extensions: [gnome-3-38]
    plugs: [home, desktop, opengl, media-control, camera]

parts:
  sacvision:
    plugin: conda
    conda-packages:
      - qt
    conda-python-version: "3.10"
    override-build: |
      snapcraftctl build
      # Installing sacvision from the developer's anaconda repository
      conda install -y -p $SNAPCRAFT_PART_INSTALL -c luisdsaco sacvision
      # Library required by Qt that is not in the default repository at run time
      conda install -y -p $SNAPCRAFT_PART_INSTALL -c conda-forge xkeyboard-config
    stage-packages:
      - libxss1
    override-prime: |
      snapcraftctl prime
      python_header='#!/snap/sacvision/current/bin/python3.10'
      sed -i "1c ${python_header}" $SNAPCRAFT_PRIME/bin/sacvision
      unset python_header
      
