name: sacvision
summary: A demonstration of the power of computer vision technology
description: |
      This program lets to acqurire images from a camera and to apply some 
      filters. It's programmed in python and it provides a Qt GUI to
      run the operations.
version: 0.1.1
license: AGPL-3.0
icon: snap/gui/sacvision.png
grade: stable
confinement: strict
base: core24
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
compression: lzo

apps:
  sacvision:
    command: bin/sacvision
    desktop: meta/gui/sacvision.desktop
    environment:
      #DISABLE_WAYLAND: 1
      #QT_XKB_CONFIG_ROOT: $SNAP/share/X11/xkb
      #GTS_PLUGIN_PATH: $SNAP/lib/gstreamer-1.0
      #GIO_MODULE_DIR: $SNAP/usr/lib/x86_64-linux-gnu/gio/modules
      #PATH: $SNAP/usr/bin:$SNAP/bin:$PATH
      #PYTHONPATH: $SNAP/lib/python3.12/site-packages:$PYTHONPATH
    extensions: [gnome]
    plugs:
      - home
      - camera
  init:
    command: bin/sacvision-init.sh
      
parts:
  sacvision:
    plugin: python
    source: https://github.com/luisdsaco/sacvision.git
    stage-packages:
      - libodbc2
      - libmysqlclient21
      - libpq5
      - libspeechd2
      - libxkbfile1
      - libxcb-image0
      - libxcb-cursor0
      - libxcb-render0
      - libxcb-icccm4
      - libxcb-keysyms1
      - libxcb-shape0
      - glib-networking
  sacvision-init:
    plugin: dump
    source: init
    organize:
      sacvision-init.sh: bin/
